### ISSUE TITLE
"react-native": "0.63.3" 低版本使用依赖包报错

### ISSUE THREAD

**Issue by zhangkaiios** [limintao/react-native-date-picker#1]
* node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  11 | 'use strict';
  12 |
> 13 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
     |                                       ^
  14 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  15 | import typeof Button from './Libraries/Components/Button';
  16 | import typeof CheckBox from './Libraries/Components/CheckBox/CheckBox';
    at ModuleResolver.resolveDependency (/Users/zk/rrs-app2新/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/zk/rrs-app2新/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/Users/zk/rrs-app2新/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/zk/rrs-app2新/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/zk/rrs-app2新/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/zk/rrs-app2新/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/zk/rrs-app2新/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/zk/rrs-app2新/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by limintao** [comment]
请上传可复现的代码
